---
- hosts: all
  user: codecosmos
  vars_files:
    - vars/common.yml
    - vars/codecosmos_vars.yml
    - vars/couchdb_vars.yml
    - secrets/passwords.yml
  tasks:
    - name: check out nvm
      git: repo={{ nvm_repo }}
           dest={{ nvm_dest }}
           version={{ nvm_version }}
           update=no
           accept_hostkey=yes
    - name: install node
      script: scripts/install-node.sh
    - name: check out codecosmos repo
      git: repo={{ codecosmos_repo }}
           dest={{ codecosmos_src }}
           version={{ codecosmos_version }}
           accept_hostkey=yes
    - name: fetch codecosmos node deps
      command: bash -c 'source {{ nvm_sh }}; npm install'
               chdir={{ codecosmos_src }}
- hosts: all
  user: root
  vars_files:
    - vars/common.yml
    - vars/codecosmos_vars.yml
  tasks:
    - name: write out codecosmos.mime.types
      notify:
        - reload nginx
      template: dest=/etc/nginx/sites-available/codecosmos.mime.types
                src=templates/etc/nginx/sites-available/codecosmos.mime.types.j2
    - name: write out codecosmos nginx config
      notify:
        - reload nginx
      template: dest=/etc/nginx/sites-available/codecosmos.conf
                src=templates/etc/nginx/sites-available/codecosmos.conf.j2
    - name: enable codecosmos nginx config
      notify:
        - reload nginx
      file: src=/etc/nginx/sites-available/codecosmos.conf
            path=/etc/nginx/sites-enabled/codecosmos.conf
            state=link
    - name: disable default nginx config
      notify:
        - reload nginx
      file: path=/etc/nginx/sites-enabled/default
            state=absent
    - name: nginx service
      service: name=nginx state=started enabled=yes
  handlers:
    - name: reload supervisord
      command: supervisorctl reread
    - name: reload nginx
      command: service nginx reload
