---
- hosts: all
  user: couchdb
  vars_files:
    - vars/couchdb_vars.yml
  tasks:
    - name: check out couchdb repo
      git: repo={{ couchdb_repo }}
           dest={{ couchdb_src }}
           version={{ couchdb_version }}
           update=no
    - name: bootstrap couchdb
      command: ./bootstrap
               chdir={{ couchdb_src }}
               creates={{ couchdb_src }}/configure
    - name: configure couchdb
      command: ./configure --disable-docs --prefix={{ couchdb_dest }}
               chdir={{ couchdb_src }}
               creates={{ couchdb_src }}/Makefile
    - name: build and install couchdb
      command: make all install
               chdir={{ couchdb_src }}
               creates={{ couchdb_dest }}
    - name: configure couchdb
      copy: dest="{{ couchdb_dest }}/{{ couchdb_ini }}" src={{ couchdb_ini }}
- hosts: all
  user: root  
  vars_files:
    - vars/couchdb_vars.yml
  tasks:
    - name: couchdb in init.d
      file: src={{ couchdb_dest }}/etc/init.d/couchdb
            path=/etc/init.d/couchdb
            state=link
    - name: couchdb service
      service: name=couchdb state=started enabled=yes
    